# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
crypttabOptions:            luks
mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime,compress=zstd:3,ssd,discard=async
    ext4: defaults,noatime
    xfs: defaults,noatime
    vfat: defaults,noatime,umask=0077
    efi: defaults,noatime,umask=0077
