# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
dontChroot: false
timeout: 3600
script:
    - "-dracut -f --no-hostonly"
    - "sh -c 'if [ -f /etc/locale.conf ]; then . /etc/locale.conf; if [ -n \"$LANG\" ] && [ -f /etc/sysconfig/language ]; then sed -i \"s/^RC_LANG=.*/RC_LANG=\\\"$LANG\\\"/\" /etc/sysconfig/language; fi; fi'"
i18n:
    name: "Rebuilding initramfs and finalizing system settings..."
